/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.constellation.common.database.jooq;


import dev.feldmann.constellation.common.database.jooq.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConstellationCommon extends SchemaImpl {

    private static final long serialVersionUID = -682640530;

    /**
     * The reference instance of <code>constellation_common</code>
     */
    public static final ConstellationCommon CONSTELLATION_COMMON = new ConstellationCommon();

    /**
     * The table <code>constellation_common.users</code>.
     */
    public final Users USERS = dev.feldmann.constellation.common.database.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private ConstellationCommon() {
        super("constellation_common", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Users.USERS);
    }
}
