/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.constellation.common.database.jooq;


import dev.feldmann.constellation.common.database.jooq.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>constellation_common</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_NICKNAME = Indexes0.USERS_NICKNAME;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_UUID = Indexes0.USERS_UUID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERS_NICKNAME = Internal.createIndex("nickname", Users.USERS, new OrderField[] { Users.USERS.NICKNAME }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_UUID = Internal.createIndex("uuid", Users.USERS, new OrderField[] { Users.USERS.UUID }, true);
    }
}
