/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.constellation.common.database.jooq;


import dev.feldmann.constellation.common.database.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in constellation_common
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>constellation_common.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
