/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.constellation.common.repositories.user.jooq.tables.records;


import dev.feldmann.constellation.common.repositories.user.jooq.tables.Users;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record5<ULong, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1473184641;

    /**
     * Setter for <code>users.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>users.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>users.uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>users.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>users.nickname</code>.
     */
    public void setNickname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>users.nickname</code>.
     */
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>users.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>users.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>users.last_login</code>.
     */
    public void setLastLogin(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>users.last_login</code>.
     */
    public Timestamp getLastLogin() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<ULong, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<ULong, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.UUID;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.NICKNAME;
    }

    @Override
    public Field<Timestamp> field4() {
        return Users.USERS.CREATED_AT;
    }

    @Override
    public Field<Timestamp> field5() {
        return Users.USERS.LAST_LOGIN;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUuid();
    }

    @Override
    public String component3() {
        return getNickname();
    }

    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    @Override
    public Timestamp component5() {
        return getLastLogin();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUuid();
    }

    @Override
    public String value3() {
        return getNickname();
    }

    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    @Override
    public Timestamp value5() {
        return getLastLogin();
    }

    @Override
    public UsersRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setNickname(value);
        return this;
    }

    @Override
    public UsersRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value5(Timestamp value) {
        setLastLogin(value);
        return this;
    }

    @Override
    public UsersRecord values(ULong value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(ULong id, String uuid, String nickname, Timestamp createdAt, Timestamp lastLogin) {
        super(Users.USERS);

        set(0, id);
        set(1, uuid);
        set(2, nickname);
        set(3, createdAt);
        set(4, lastLogin);
    }
}
